spring.application.name=biblioteca
spring.datasource.url=jdbc:postgresql://localhost:5432/biblioteca
spring.datasource.username=postgres
spring.datasource.password=admin
spring.jpa.hibernate.ddl-auto=update
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
app.jwt.secret=cambia-esta-clave-secreta-de-minimo-32-caracteres-123456
app.jwt.expiration-ms=86400000
